.Dd December 27, 2016
.Dt SVT 1
.Os svt VERSION
.Sh NAME
.Nm svt
.Nd simple virtual terminal
.
.
.Sh SYNOPSIS
.
.Nm
.Op Fl v
.Op Fl t Ar title
.Op Fl c Ar cmd-fifo
.Op Fl o Ar dump-file
.Op Ar command Ar ...
.
.
.Sh DESCRIPTION
.
.Nm
is a simple virtual terminal which allows for dumping & scrollback.
.Pp
As a console window manager it tries to make it easy to work with multiple
console based applications.
.
.Bl -tag -width 8
.It Fl v
Print version information to standard output and exit.
.
.It Fl t Ar title
Set a static terminal
.Ar title
and don't change it to the one of the currently focused window.
.
.It Fl c Ar cmd-fifo
Open or create the named pipe
.Pa cmd-fifo
and look for commands to execute which were defined in
.Pa config.h .
.
.It Fl o Ar dump-file
Open or create the file
.Pa dump-file
and write the terminal buffer to it
.
.It Ar command Ar ...
Execute
.Ar command
(s), each in a separate window.
.El
.
.
.Sh ENVIRONMENT VARIABLES
.
.Bl -tag -width 8
.It Ev SVT
Each process spawned by svt will have this variable set to the svt version
it is running under.
.
.It Ev SVT_CMD_FIFO
If the -c command line argument was specified upon svt startup, this variable
will be set to the file name of the named pipe. Thus allowing the process
to send commands back to svt.
.
.It Ev SVT_DUMP_FILE
If the -o command line argument was specified upon svt startup, this variable
will be set to the file name of the dump file.
.
.It Ev SVT_TERM
By default svt uses its own terminfo file and therefore sets
.Ev TERM=svt
within the client windows. This can be overridden by setting the
.Ev SVT_TERM
environment variable to a valid terminal name before launching svt.
.
.
.Sh FILES
.
.Nm
is customized by creating a custom
.Pa config.h
and (re)compiling the source code.
This keeps it fast, secure and simple.
.
.
.Sh SEE ALSO
.
.Xr abduco 1  ,
.Xr bmac 1 ,
.Xr itty 1
.
.
.Sh AUTHOR
.
svt is written
.An Jeremy Bobbin Aq Mt jer at jer.cx
